class JobDecorator < Draper::Base

  include ActionView::Helpers::NumberHelper

  decorates :job

  # Accessing Helpers
  #   You can access any helper via a proxy
  #
  #   Normal Usage: helpers.number_to_currency(2)
  #   Abbreviated : h.number_to_currency(2)
  #
  #   Or, optionally enable "lazy helpers" by including this module:
  #     include Draper::LazyHelpers
  #   Then use the helpers with no proxy:
  #     number_to_currency(2)

  # Defining an Interface
  #   Control access to the wrapped subject's methods using one of the following:
  #
  #   To allow only the listed methods (whitelist):
  #     allows :method1, :method2
  #
  #   To allow everything except the listed methods (blacklist):
  #     denies :method1, :method2

  # Presentation Methods
  #   Define your own instance methods, even overriding accessors
  #   generated by ActiveRecord:
  #
  #   def created_at
  #     h.content_tag :span, attributes["created_at"].strftime("%a %m/%d/%y"),
  #                   :class => 'timestamp'
  #   end
  #

  def thumbnail_url
    company.image.url(:thumbnail)
  end

  def truncated_title
    (title.length > 105) ? (title.slice(0, 105) + "...") : title
  end

  def company_name
    company.name
  end

  def salary_comp?
    salary_low.present? && salary_high.present?
  end

  def formatted_salary_low
    number_to_currency((salary_low || 0) * 1000, precision: 0)
  end

  def formatted_salary_high
    number_to_currency((salary_high || 0) * 1000, precision: 0)
  end

  def hourly_comp?
    hourly_low.present? && hourly_high.present?
  end

  def formatted_hourly_low
    number_to_currency(hourly_low, precision: 2)
  end

  def formatted_hourly_high
    number_to_currency(hourly_high, precision: 2)
  end

  def equity_comp?
    equity_low.present? && equity_high.present?
  end

  def formatted_equity_low
    number_to_percentage(equity_low, precision: 2, strip_insignificant_zeros: true)
  end

  def formatted_equity_high
    number_to_percentage(equity_high, precision: 2, strip_insignificant_zeros: true)
  end

  def city_name
    city.name
  end

  def posted_date
    created_at.to_date.to_s(:short)
  end

  def posted_date_timestamp
    created_at.to_date.to_time.to_i
  end

  def expires_date
    expires_on.to_date.to_s(:long)
  end

  def clickthrough
    link.presence || company.homepage_url
  end

end
